from sqlalchemy import Column, String, Date, ForeignKey, JSON
from sqlalchemy.orm import relationship
from shared.models.base import BaseModel

class VoterProfile(BaseModel):
    """
    Core Election Identity model. Decoupled from authentication identity (users table).
    """
    __tablename__ = "voter_profiles"

    id = Column(String, primary_key=True)
    user_id = Column(String, unique=True, index=True, nullable=False) # Link to auth-service.User

    # ECI Identity
    epic_number = Column(String, unique=True, index=True, nullable=True) # Generated by EPIC service
    part_no = Column(String)
    serial_no = Column(String)

    # Personal Details
    first_name = Column(String, nullable=False)
    last_name = Column(String, nullable=False)
    father_name = Column(String)
    mother_name = Column(String)
    spouse_name = Column(String)
    date_of_birth = Column(Date, nullable=False)
    gender = Column(String, nullable=False)

    # Address & Hierarchy (Relational)
    address_line1 = Column(String, nullable=False)
    address_line2 = Column(String)
    pincode = Column(String, nullable=False)
    
    # Strict Hierarchy Foreign Keys
    state_id = Column(String, ForeignKey("states.id"), nullable=False)
    district_id = Column(String, ForeignKey("districts.id"), nullable=False)
    pc_id = Column(String, ForeignKey("parliamentary_constituencies.id"), nullable=False)
    ac_id = Column(String, ForeignKey("assembly_constituencies.id"), nullable=False)
    polling_booth_id = Column(String, ForeignKey("polling_booths.id"), nullable=False)

    # Aadhaar Security (DPDP Compliant Vaulting)
    aadhaar_hash = Column(String, unique=True, index=True) # For duplicate checking
    aadhaar_last4 = Column(String(4)) # For UI masking
    encrypted_aadhaar = Column(String) # Encrypted value, requiring KMS to decrypt
    aadhaar_vault_ref = Column(String) # Optional reference to external secure vault

    # Verification Lifecycle
    verification_status = Column(String, default="pending") # pending, under_review, approved, rejected
    is_verified = Column(String, default="false") # True when approved and EPIC generated
    
    # Relationships
    state = relationship("State")
    district = relationship("District")
    parliamentary_constituency = relationship("ParliamentaryConstituency")
    assembly_constituency = relationship("AssemblyConstituency")
    polling_booth = relationship("PollingBooth")
